### ISSUE TITLE
2.1 Update doesn't allow manual specification of Lifx via config.yaml

### ISSUE THREAD

**Issue by mekenthompson** [Djelibeybi/ha-lifx-beta#2]
Since update, LIFX config doesn't allow "broadcast" in configuration.yaml for LIFX integration.

Ie. I've still had a LIFX includes file that has all my LIFX static IPs listed out. 
```
lifx:
  light:
    - broadcast: 192.168.3.156 #LIFX-Balcony-1
    - .....
    - .....
```
Although I originally did this as dynamic discovery was unreliable and I've got 92 lights lights in total. I've commented my LIFX include out for now and will give the dynamic discovery more of a test, initally just tested once for startup times then reverted back.

Would be good to support static definition per above though as an option, especially for folks already using older lifx integration if they migrate.
